name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build: 
     runs-on: ubuntu-latest
     env:
       WORK_DIR: react-app
     
     steps: 
      - uses: actions/checkout@v2
      - run: |
          cd $WORK_DIR
          npm ci
      - run: |
          cd $WORK_DIR
          npm run format:check
      - run: |
          cd $WORK_DIR
          npm test -- --coverage
        env:
          CI: true
